// <auto-generated />
namespace ProjConsultorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class banco7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(banco7));
        
        string IMigrationMetadata.Id
        {
            get { return "202010252259469_banco7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
